language: ruby
env:
  - JENKINS_VERSION=1.651.3
  - JENKINS_VERSION=2.89.2
  - JENKINS_VERSION=latest
jdk:
  - oraclejdk8
  - openjdk7
rvm:
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
matrix:
  exclude:
    - env: JENKINS_VERSION=1.651.3
      jdk: openjdk7
      rvm: 1.9.3
    - env: JENKINS_VERSION=2.89.2
      jdk: openjdk7
    - env: JENKINS_VERSION=latest
      jdk: openjdk7
group: deprecated-2017Q3
sudo: required
